### ISSUE TITLE
now is animating. cant override animator

### ISSUE THREAD

**Issue by KuljeetSingh96** [MasayukiSuda/AnimateHorizontalProgressBar#4]
W/com.daasuu.ahp.AnimateHorizontalProgressBar: now is animating. cant override animator

I am getting this error when ever I am going to use progress bar 
       mediaPlayer.setOnBufferingUpdateListener((mp, percent) -> {
            if (!feedItem.iscomplete()) {
                feedItem.setTotalLength(mp.getDuration());
                feedItem.setCurrentLength(mp.getCurrentPosition());
                audioProgress.setMax(mp.getDuration());
                audioProgress.setProgressWithAnim(mp.getCurrentPosition());
            }
        });

Let me know solution for this

**Comment by MasayukiSuda** [comment]
call cancelAnimation()
```
audioProgress.setMax(mp.getDuration());
audioProgress.cancelAnimation();
audioProgress.setProgressWithAnim(mp.getCurrentPosition());
```

**Comment by KuljeetSingh96** [comment]
okay thanks but i have used default seek bar instead and is working fine.
